import type { Monaco } from "@monaco-editor/react";

export function configureMonacoThemes(monaco: Monaco): void {
  monaco.editor.defineTheme("hc-oled", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "38bdf8", fontStyle: "bold" },
      { token: "keyword.sql", foreground: "38bdf8", fontStyle: "bold" },
      { token: "predefined", foreground: "c084fc", fontStyle: "bold" },
      { token: "predefined.sql", foreground: "c084fc", fontStyle: "bold" },
      { token: "type", foreground: "f59e0b", fontStyle: "bold" },
      { token: "type.sql", foreground: "f59e0b", fontStyle: "bold" },
      { token: "string", foreground: "34d399" },
      { token: "string.sql", foreground: "34d399" },
      { token: "number", foreground: "fb923c" },
      { token: "number.sql", foreground: "fb923c" },
      { token: "comment", foreground: "64748b", fontStyle: "italic" },
      { token: "comment.sql", foreground: "64748b", fontStyle: "italic" },
      { token: "operator", foreground: "f472b6" },
      { token: "operator.sql", foreground: "f472b6" },
      { token: "delimiter", foreground: "facc15" },
      { token: "delimiter.parenthesis", foreground: "ffd700" },
      { token: "identifier", foreground: "f8fafc" },
      { token: "identifier.sql", foreground: "f8fafc" },
    ],
    colors: {
      "editor.background": "#000000",
      "editorGutter.background": "#000000",
      "editor.lineHighlightBackground": "#050505",
      "editorLineNumber.foreground": "#475569",
      "editorLineNumber.activeForeground": "#38bdf8",
      "editorBracketMatch.background": "#1e293b",
      "editorBracketMatch.border": "#38bdf8",
      "editorBracketHighlight.foreground1": "#ffd700",
      "editorBracketHighlight.foreground2": "#38bdf8",
      "editorBracketHighlight.foreground3": "#f472b6",
      "editorBracketHighlight.foreground4": "#34d399",
      "editorBracketHighlight.foreground5": "#c084fc",
      "editorBracketHighlight.foreground6": "#fb923c",
      "editorBracketHighlight.unexpectedBracket.foreground": "#ef4444",
    },
  });
}

export const MONACO_DEFAULT_OPTIONS = {
  fontSize: 13,
  fontFamily: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace",
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  wordWrap: "on" as const,
  lineNumbers: "on" as const,
  glyphMargin: false,
  folding: true,
  lineDecorationsWidth: 10,
  lineNumbersMinChars: 3,
  automaticLayout: true,
  tabSize: 2,
  cursorBlinking: "smooth" as const,
  cursorSmoothCaretAnimation: "on" as const,
  smoothScrolling: true,
  renderLineHighlight: "all" as const,
  suggestOnTriggerCharacters: true,
  quickSuggestions: { other: true, comments: false, strings: true },
};
